[tools]
uv = "latest"

[settings]
python.uv_venv_auto = true

[tasks.types]
description = "Check types across all code"
run = 'uvx ty check'

[tasks.lint]
run = 'uvx ruff check'

[tasks.format]
run = 'uvx ruff format'

[tasks.ci]
depends = ["types", "lint"]
