[tools]
uv = "latest"

[settings]
python.uv_venv_auto = true

[tasks.types]
description = "Check types across all code"
run = 'uv run --package handlebar-google-adk ty check packages/core/src packages/google-adk/src'

[tasks.lint]
run = 'uv run ruff check'

[tasks.format]
run = 'uv run ruff format'
